### PR TITLE
date-fns added to test-suit

### PR DESCRIPTION
**Pull request by matiasbian**
Hi! i added date-fns library to the test suite.

### CODE REVIEW

**Review by terodox — CHANGES_REQUESTED** [review]
Awesome addition!!

Could you please update the README with this additional info?

thanks again for the addition!!

**Comment by matiasbian** [comment]
Thanks @terodox !

Sure! I'll add the changes to the readme in a few minutes

**Comment by matiasbian** [comment]
Done!. I updated the readme. Tell me what you think

**Review by terodox — APPROVED** [review]
Great update to the README! Thank you again!!

**Pull request merged**
